version: 2

build:
  image: latest

python:
  version: 3.6
  install:
    - requirements: requirements/requirements.txt
    - requirements: requirements/requirements_docs.txt
    - method: setuptools
      path: .
  system_packages: true

sphinx:
  configuration: docs/conf.py
