version: 2


python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: true

sphinx:
  configuration: docs/conf.py
