name: Build
description: builds xtgeo

inputs:
  python-version:
    required: true


runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      run: python -m pip install pip==21.3.1
      shell: bash
      if: ${{ inputs.os }} != windows-latest

    - name: install xtgeo
      run: pip install .
      shell: bash
