name: "Set up for tests"
description: "Set up the xtgeo test environment"

inputs:
    python-version:
        required: true

runs:
  using: "composite"
  steps:
      - uses: "./.github/actions/build-xtgeo"
        with:
          python-version: ${{ inputs.python-version }}
      - run: git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
        shell: bash
      - run: pip install -r requirements/requirements_test.txt
        shell: bash
