pipeline {
    agent { label 'scout-ci7' }
    environment {
        WORKING_DIR = sh(script: 'pwd', , returnStdout: true).trim()
    }
    stages {
        stage('test') {
            steps {
                sh '''
                  source /opt/rh/devtoolset-9/enable
                  git clone --depth=1 https://github.com/equinor/xtgeo-testdata
                  set +e
                  source $ROXENVBASH $RMS_VERSION
                  set -e
                  unset PYTHONPATH
                  python -m virtualenv xtgeo_env --system-site-packages
                  source xtgeo_env/bin/activate
                  pip install -r requirements/requirements.txt
                  pip install -r requirements/requirements_dev.txt
                  pip install -r requirements/requirements_test.txt
                  pip install . --ignore-installed
                  export XTG_TESTPATH=./xtgeo-testdata/
                  python -m pytest -m requires_roxar
                '''
            }
        }
    }

    post {
        cleanup {
            deleteDir()
        }
    }
}
