name: Setup xtgeo
description: Set up the xtgeo test environment

inputs:
  python-version:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Build and install xtgeo
      shell: bash
      run: |
        python -m pip install -U pip
        python -m pip install ".[dev]"
