name: Setup xtgeo
description: Set up the xtgeo test environment

inputs:
  python-version:
    required: true
    type: string
  os:
    required: true
    default: ubuntu-latest
    type: string

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    
    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}
              
    - name: Install Windows dependencies
      if: ${{ inputs.os == 'windows-latest' }}
      shell: bash
      run: |
        git -C C:/vcpkg pull
        vcpkg install --triplet x64-windows

    - name: Install macOS dependencies
      if: ${{ inputs.os == 'macos-latest' || inputs.os == 'macos-13' }}
      # HDF5 needed for pytables+Python 3.10+
      shell: bash
      run: |
        brew install hdf5 eigen fmt
        echo "HDF5_DIR=/opt/homebrew" >> $GITHUB_ENV

    - name: Install Linux dependencies
      if: ${{ inputs.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        sudo apt-get install libeigen3-dev libfmt-dev

    - name: Build and install xtgeo
      shell: bash
      run: |
        uv venv
        uv pip install -U pip
        uv pip install ".[dev]" -v
