# build and test some end points
name: integration test opm

on:
  pull_request:
    branches: [master]

jobs:
  build_pywheels:
    name: PY ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # All python versions are tested on linux, only selected versions on win and osx
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up OPM
        run: >
          sudo apt install software-properties-common &&
          sudo apt-add-repository ppa:opm/ppa &&
          sudo apt install mpi-default-bin libopm-simulators-bin


      - name: Install xtgeo
        run: >
          python -m pip install pip -U &&
          python -m pip install .

      - name: Small version test
        run: python -c "import xtgeo; print(xtgeo.__version__)"

      - name: Full test
        run: >
          python -m pip install -r requirements/requirements_test.txt &&
          git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata &&
          HAS_OPM=1 python -m pytest -m requires_opm --disable-warnings -x --hypothesis-profile ci
