name: buildsall

on:
  pull_request:
    branches: [master]

env:
  CIBW_BEFORE_ALL_LINUX: "sh scripts/swig_manylinux.sh"
  CIBW_BEFORE_ALL_WINDOWS: "choco install -y --no-progress --allow-empty-checksums -r swig --version=4.0.1"
  CIBW_BEFORE_ALL_MACOS: "brew install swig"
  CIBW_BEFORE_TEST: |
    cd {project}
    pip install -r requirements/requirements.txt
    pip install -r requirements/requirements_test.txt

  CIBW_TEST_COMMAND: |
    cd {project}
    git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
    pytest tests --disable-warnings

  CIBW_BUILD: |
    cp36-manylinux_x86_64
    cp36-macosx_x86_64
    cp36-win_amd64

jobs:
  build_multiwheels:
    name: CIBW PY36 on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: |
          python -m pip install pip -U
          python -m pip install wheel
          python -m pip install cibuildwheel==1.5.5

      - name: Build wheels and test
        run: |
          python -m cibuildwheel --output-dir wheelhouse

  build_pywheels:
    name: PY ${{ matrix.python-version }} on linux

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install xtgeo
        run: |
          pip install pip -U
          pip install .

      - name: Test with pytest
        run: |
          git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
          pip install -r requirements/requirements_test.txt
          pytest --disable-warnings -x

      - name: Build docs
        run: |
          pip install -r requirements/requirements_docs.txt
          sphinx-build -W docs tmp/docs
