name: builds

on:
  push:
    branches: [master]

jobs:
  build_pywheels:
    name: PY ${{ matrix.python-version }} on linux

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install xtgeo
        run: |
          pip install pip -U
          pip install .

      - name: Test with pytest
        run: |
          git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
          pip install -r requirements/requirements_test.txt
          pytest --disable-warnings -x --hypothesis-profile ci --generate-plots
