# build and test some end points
name: buildsall

on:
  pull_request:
    branches: [master]

jobs:
  build_pywheels:
    name: PY ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # All python versions are tested on linux, only selected versions on win and osx
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            python-version: 3.6
          - os: macos-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.8

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install swig (osx)
        if: matrix.os == 'macos-latest'
        run: brew install swig

      - name: Install swig (win)
        if: matrix.os == 'windows-latest'
        run: "choco install -y --no-progress --allow-empty-checksums -r swig --version=4.0.1"

      - name: Install xtgeo
        run: >
          pip install pip -U &&
          pip install .

      - name: Small version test
        run: python -c "import xtgeo; print(xtgeo.__version__)"

      - name: Full test
        run: >
          pip install -r requirements/requirements_test.txt &&
          git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata &&
          pytest --disable-warnings -x

      - name: Build docs
        run: >
          pip install -r requirements/requirements_docs.txt &&
          sphinx-build -W docs tmp/docs
