name: buildsall

on:
  pull_request:
    branches: [master]

env:
  CIBW_BEFORE_ALL_LINUX: "sh scripts/swig_manylinux.sh"
  CIBW_BEFORE_ALL_WINDOWS: "choco install -y --no-progress --allow-empty-checksums -r swig --version=4.0.1"
  CIBW_BEFORE_ALL_MACOS: "brew install swig"
  CIBW_BEFORE_TEST: |
    cd {project}
    pip install -r requirements/requirements.txt
    pip install -r requirements/requirements_test.txt

  CIBW_TEST_COMMAND: |
    cd {project}
    git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
    pytest tests --disable-warnings

  CIBW_BUILD: |
    cp39-manylinux_x86_64
    cp38-macosx_x86_64
    cp38-win_amd64

# Verify that wheel build jobs succeed
jobs:
  build_multiwheels:
    name: CIBW PY38 or 39 on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: |
          python -m pip install pip -U
          python -m pip install wheel
          python -m pip install cibuildwheel

      - name: Build wheels and test
        run: |
          python -m cibuildwheel --output-dir wheelhouse

  build_pywheels:
    name: PY ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    # All python versions are tested on linux, only first and last on win and osx
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            python-version: 3.6
          - os: macos-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.8

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install swig (osx)
        if: matrix.os == 'macos-latest'
        run: brew install swig

      - name: Install swig (win)
        if: matrix.os == 'windows-latest'
        run: |
          (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.2.zip","swigwin-4.0.2.zip");
          Expand-Archive .\swigwin-4.0.2.zip .;
          echo "$((Get-Item .).FullName)/swigwin-4.0.2" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install xtgeo
        run: |
          pip install pip -U
          pip install .

      - name: Test with pytest
        run: |
          git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
          pip install -r requirements/requirements_test.txt
          pytest --disable-warnings -x

      - name: Build docs
        run: |
          pip install -r requirements/requirements_docs.txt
          sphinx-build -W docs tmp/docs
