name: CodSpeed

on:
  push:
    branches: [main, "version-*"]
  pull_request:
    branches: [main, "version-*"]
  # Allow CodSpeed to trigger backtest performance analysis to generate initial data
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup xtgeo
        uses: "./.github/actions/setup_xtgeo"
        with:
          python-version: "3.11"
          os: ubuntu-latest

      - name: Setup testdata
        uses: "./.github/actions/setup_testdata"

      - name: Run benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f # v4.18.1
        with:
          mode: simulation
          run: uv run pytest tests --codspeed --disable-warnings
