name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  UV_FROZEN: true
  OMP_NUM_THREADS: 1

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup xtgeo
        uses: "./.github/actions/setup_xtgeo"
        with:
          python-version: "3.13"
          os: ubuntu-latest

      - name: Setup testdata
        uses: "./.github/actions/setup_testdata"

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
        with:
          mode: simulation
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: |
            uv run --no-sync pytest tests/ --codspeed --disable-warnings
