name: Build & Publish

on:
  pull_request:
    branches: [main, "version-*"]
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
        python: ["cp311", "cp312", "cp313", "cp314"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install cibuildwheel
        run: |
          uv venv
          uv pip install -U pip cibuildwheel twine

      - name: Build wheels
        run: uv run cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python }}-*

      - name: Check metadata
        run: uv run twine check wheelhouse/*

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        with:
          name: cibw-${{ matrix.os }}-${{ runner.arch }}-${{ matrix.python }}
          path: wheelhouse/*.whl

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    environment:
      name: pypi
      url: https://pypi.org/project/xtgeo
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: cibw-*
          path: wheelhouse
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
        with:
          skip-existing: true
          packages-dir: wheelhouse
          verbose: true
