name: VDS Test

on:
  push:
    branches: [main, "version-*"]
  pull_request:
    branches: [main, "version-*"]
  # release:
  #   types:
  #     - published
  # schedule:
  #   # Run nightly to check that tests are working with latest dependencies
  #   - cron: "0 0 * * *"

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Eigen3 via vcpkg
        run: vcpkg install eigen3:x64-windows

      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup_xtgeo"
        with:
          python-version: 3.11

      - name: Set vcpkg toolchain
        run: |
          echo "CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV

      - name: Setup testdata
        uses: "./.github/actions/setup_testdata"

      - name: Run tests (Linux/macOS)
        run: |
          pip install openvds
          python vds_test2.py -v
          python vds_test.py -v
